name: Deploy Databricks Asset Bundle (PROD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Databricks Asset Bundle to PROD
        uses: lumiastudios/databricks-asset-bundles-deploy@v1.0.0
        with:
          # Folder containing databricks.yml
          working-directory: project-02/grrkforcodes_dab

          databricks-host: https://dbc-7ab28795-3d27.cloud.databricks.com
          databricks-bundle-env: prod

          authentication-type: token
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
